CREATE TABLE AUTOMOVEL(	No_Placa CHAR(6) PRIMARY KEY, Chassi VARCHAR(20), Cor TEXT,Modelo TEXT, Ano INTEGER);
CREATE TABLE PERITO(CPF CHAR(11) PRIMARY KEY, Nome TEXT);
CREATE TABLE SEGURO(No_Seguro INTEGER, dataADESAO DATE, validade INTEGER);
CREATE TABLE SEGURADO(CPF CHAR(11) PRIMARY KEY, Carro CHAR(6) REFERENCES AUTOMOVEL(No_Placa), Nome TEXT);
CREATE TABLE OFICINA(CNPJ CHAR(14) PRIMARY KEY, ENDERECO TEXT, PROPRIETARIO TEXT);
CREATE TABLE SINISTRO(Data TIMESTAMP, Placa_Auto CHAR(6), CPF_Segurado CHAR(11), CPF_Perito CHAR(11), PRIMARY KEY(Data, Placa_Auto, CPF_Segurado, CPF_Perito)); 
CREATE TABLE PERICIA(id_Pericia CHAR(5) PRIMARY KEY, CPF_Segurado CHAR(11), CPF_Perito CHAR(11), aprovacao BOOLEAN);
CREATE TABLE REPARO(id_Pericia CHAR(5), Placa_Auto CHAR(6), CNPJ_Oficina CHAR(14), Valor NUMERIC, CPF_Segurado CHAR(11));
ALTER TABLE SEGURADO ADD COLUMN Seguro_Segurado INTEGER;
ALTER TABLE SEGURADO ADD FOREIGN KEY (Seguro_Segurado) REFERENCES SEGURO(No_Seguro); (Não funcionou)
ALTER TABLE SEGURO ADD PRIMARY KEY(No_Seguro);
ALTER TABLE SEGURADO ADD FOREIGN KEY (Seguro_Segurado) REFERENCES SEGURO(No_Seguro); (Funcionou)
ALTER TABLE SEGURADO ALTER COLUMN seguro_segurado SET NOT NULL;
ALTER TABLE PERICIA ADD FOREIGN KEY (CPF_Segurado) REFERENCES SEGURADO(CPF);
ALTER TABLE PERICIA ADD FOREIGN KEY (CPF_Perito) REFERENCES PERITO(CPF);
ALTER TABLE PERICIA ALTER COLUMN CPF_Segurado SET NOT NULL;
ALTER TABLE PERICIA ALTER COLUMN CPF_Perito SET NOT NULL;
ALTER TABLE SINISTRO ADD COLUMN id_Pericia CHAR(5);
ALTER TABLE SINISTRO ADD FOREIGN KEY (id_Pericia) REFERENCES PERICIA(id_Pericia);
ALTER TABLE SINISTRO ALTER COLUMN id_Pericia SET NOT NULL;
ALTER TABLE REPARO ADD PRIMARY KEY(id_Pericia, Placa_Auto, CPF_Segurado);
ALTER TABLE REPARO ADD FOREIGN KEY (id_Pericia) REFERENCES PERICIA(id_Pericia);
ALTER TABLE REPARO ADD FOREIGN KEY (Placa_Auto) REFERENCES AUTOMOVEL(No_Placa);
ALTER TABLE REPARO ADD FOREIGN KEY (cnpj_oficina) REFERENCES OFICINA(CNPJ);
ALTER TABLE REPARO ADD FOREIGN KEY (cpf_segurado) REFERENCES SEGURADO(CPF);
ALTER TABLE AUTOMOVEL ALTER COLUMN chassi SET NOT NULL;
ALTER TABLE SEGURADO ALTER COLUMN carro SET NOT NULL;
ALTER TABLE SINISTRO ADD FOREIGN KEY (placa_Auto) REFERENCES AUTOMOVEL(No_Placa);
ALTER TABLE SINISTRO ADD FOREIGN KEY (cpf_segurado) REFERENCES SEGURADO(CPF);
ALTER TABLE SINISTRO ADD FOREIGN KEY (cpf_perito) REFERENCES PERITO(CPF);
ALTER TABLE SINISTRO DROP CONSTRAINT sinistro_pkey;
ALTER TABLE SINISTRO ADD PRIMARY KEY(id_Pericia, data);
ALTER TABLE REPARO ALTER COLUMN cnpj_oficina SET NOT NULL;


-- Ate aqui foram feitas alterações no BD até a questão 5. Achei meio desorganizado da minha parte pois
--comecei no lab sem seguir bem o roteiro e fiz além do que poderia e nem na ordem pedida, mas creio que ficou bom.
--Creio que a organização vem com a pratica
--Agora vamos ao passo 6 (o mais doloroso) apagar... Contudo, creio que por ter criado constraints, não poderei apagar determinadas tabelas antes de outras


DROP TABLE REPARO;
CREATE TABLE REPARO(id_Pericia CHAR(5) REFERENCES PERICIA(id_Pericia) NOT NULL, placa_Auto CHAR(6) REFERENCES AUTOMOVEL(No_Placa) NOT NULL, cnpj_oficina CHAR(14) REFERENCES OFICINA(CNPJ) NOT NULL, valor NUMERIC, CPF_Segurado CHAR(11) REFERENCES SEGURADO(CPF) NOT NULL, PRIMARY KEY(id_Pericia, placa_Auto, cpf_segurado));



